name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          /home
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/arm/v7

    -  
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.armhf
          push: true
          tags:  ghcr.io/paganuzzi/dockerngrok:latest
          platforms: linux/arm/v7
